[global]
developmentMode = false

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50
fileWatcherType = "none"
maxMessageSize = 200

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
