[global]
developmentMode = false

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
